"""
Download gridding_kernel.cc from GitHub, extract all KernelDB entries,
and write radiomesh/generated/_es_kernel_params.py containing the kernel parameters.
"""

import importlib.resources
import re
import urllib.request
from pathlib import Path

import radiomesh.generated

URL = (
  "https://raw.githubusercontent.com/mreineck/ducc/refs/heads/ducc0"
  "/src/ducc0/math/gridding_kernel.cc"
)

OUTPUT_FILENAME = "_es_kernel_params.py"

ENTRY_RE = re.compile(
  r"\{\s*"
  r"(\d+)"  # width
  r"\s*,\s*"
  r"([0-9.e+-]+)"  # oversampling
  r"\s*,\s*"
  r"([0-9.e+-]+)"  # epsilon
  r"\s*,\s*"
  r"([0-9.e+-]+)"  # beta
  r"\s*,\s*"
  r"([0-9.e+-]+)"  # e0
  r"\s*,\s*"
  r"(\d+)"  # ndim
  r"\s*,\s*"
  r"(true|false)"  # single
  r"\s*\}"
)


def download(url: str) -> str:
  with urllib.request.urlopen(url) as resp:
    return resp.read().decode()


def parse_and_write(source: str, path: Path) -> int:
  """Parse KernelDB entries from C++ source and write the Python module.

  Returns the number of entries written.
  """
  m = re.search(r"const vector<KernelParams> KernelDB \{(.*?)\};", source, re.DOTALL)
  if not m:
    raise ValueError("KernelDB block not found in source")

  block = m.group(1)

  lines = [
    "# Auto-generated by scripts/gen_kernel_params.py — DO NOT EDIT",
    "from __future__ import annotations",
    "from typing import NamedTuple",
    "",
    "",
    "class KernelParams(NamedTuple):",
    '  """Tabulated Kernel Parameters"""',
    "",
    "  support: int         # kernel width (support)",
    "  oversampling: float  # oversampling factor",
    "  epsilon: float       # error bound",
    "  beta: float          # beta parameter (scale by width before use)",
    "  mu: float            # exponent in (1-x^2)^mu",
    "  ndim: int            # number of dimensions this entry applies to",
    "  single: bool         # whether single precision is sufficient",
    "",
    "",
    "KERNEL_DB: tuple[KernelParams, ...] = (",
  ]

  count = 0
  for em in ENTRY_RE.finditer(block):
    width, oversampling, epsilon, beta, e0, ndim, single = em.groups()
    lines.append(
      f"  KernelParams("
      f"{int(width)}, {float(oversampling)}, {float(epsilon)!r}, "
      f"{float(beta)!r}, {float(e0)!r}, "
      f"{int(ndim)}, {single == 'true'}),"
    )
    count += 1

  lines.append(")")
  lines.append("")

  path.write_text("\n".join(lines))
  print(f"Written {count} entries to {path}")
  return count


def generate_kernel_params():
  print(f"Downloading {URL} ...")
  source = download(URL)

  output_path = Path(
    str(importlib.resources.files(radiomesh.generated) / OUTPUT_FILENAME)
  )
  count = parse_and_write(source, output_path)
  print(f"Extracted {count} kernel entries.")


if __name__ == "__main__":
  generate_kernel_params()
