"""
Download gridding_kernel.cc from GitHub, extract all KernelDB entries,
and write radiomesh/generated/_es_kernel_params.py containing the kernel parameters.
"""

import importlib.resources
import re
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import radiomesh.generated

URL = (
  "https://raw.githubusercontent.com/mreineck/ducc/refs/heads/ducc0"
  "/src/ducc0/math/gridding_kernel.cc"
)

OUTPUT_FILENAME = "_es_kernel_params.py"


@dataclass
class KernelParams:
  """Mirrors the C++ KernelParams struct in gridding_kernel.h."""

  width: int  # kernel width (support)
  oversampling: float  # oversampling factor
  epsilon: float  # error bound
  beta: float  # beta parameter for the ES kernel
  e0: float  # e0 / mu parameter (exponent in (1-x^2)^e0)
  ndim: int  # number of dimensions this entry applies to
  single: bool  # whether single precision is sufficient


def download(url: str) -> str:
  with urllib.request.urlopen(url) as resp:
    return resp.read().decode()


def parse_kernel_db(source: str) -> list[KernelParams]:
  m = re.search(r"const vector<KernelParams> KernelDB \{(.*?)\};", source, re.DOTALL)
  if not m:
    raise ValueError("KernelDB block not found in source")

  block = m.group(1)

  entry_re = re.compile(
    r"\{\s*"
    r"(\d+)"  # width
    r"\s*,\s*"
    r"([0-9.e+-]+)"  # oversampling
    r"\s*,\s*"
    r"([0-9.e+-]+)"  # epsilon
    r"\s*,\s*"
    r"([0-9.e+-]+)"  # beta
    r"\s*,\s*"
    r"([0-9.e+-]+)"  # e0
    r"\s*,\s*"
    r"(\d+)"  # ndim
    r"\s*,\s*"
    r"(true|false)"  # single
    r"\s*\}"
  )

  kernels = []
  for m in entry_re.finditer(block):
    width, oversampling, epsilon, beta, e0, ndim, single = m.groups()
    kernels.append(
      KernelParams(
        width=int(width),
        oversampling=float(oversampling),
        epsilon=float(epsilon),
        beta=float(beta),
        e0=float(e0),
        ndim=int(ndim),
        single=(single == "true"),
      )
    )

  return kernels


def write_params_module(kernels: list[KernelParams], path: Path) -> None:
  lines = [
    "# Auto-generated by scripts/gen_kernel_params.py — DO NOT EDIT",
    "from __future__ import annotations",
    "from dataclasses import dataclass",
    "",
    "",
    "@dataclass(frozen=True)",
    "class KernelParams:",
    '    """Mirrors the C++ KernelParams struct in gridding_kernel.h.',
    "",
    "    Note: beta is stored as-is from the KernelDB (not pre-scaled by width).",
    '    """',
    "    support: int         # kernel width (support)",
    "    oversampling: float  # oversampling factor",
    "    epsilon: float       # error bound",
    "    beta: float          # beta parameter (scale by width before use)",
    "    mu: float            # exponent in (1-x^2)^mu",
    "    ndim: int            # number of dimensions this entry applies to",
    "    single: bool         # whether single precision is sufficient",
    "",
    "",
    "KERNEL_DB: tuple[KernelParams, ...] = (",
  ]

  for k in kernels:
    lines.append(
      f"    KernelParams("
      f"{k.width}, {k.oversampling}, {k.epsilon!r}, "
      f"{k.beta!r}, {k.e0!r}, "
      f"{k.ndim}, {k.single}),"
    )

  lines.append(")")
  lines.append("")

  path.write_text("\n".join(lines))
  print(f"Written {len(kernels)} entries to {path}")


def generate_kernel_params():
  print(f"Downloading {URL} ...")
  source = download(URL)

  kernels = parse_kernel_db(source)
  print(f"Extracted {len(kernels)} kernel entries.")

  output_path = Path(
    str(importlib.resources.files(radiomesh.generated) / OUTPUT_FILENAME)
  )
  write_params_module(kernels, output_path)


if __name__ == "__main__":
  generate_kernel_params()
